# Generated by Django 4.2.3 on 2023-08-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
    ]
